version: '3'
services:
    web:
        container_name: web_cgi
        build:
            context: .
            
        volumes:
            - ./code:/code
            - ./log/web:/var/log/nginx/web
        ports:
            - "8080:80"
        links:
            - php
    php:
        image: php:5-fpm
        volumes:
            - ./code:/code
